<?php

// $Id$
function displayridedetails_menu() {

// this code is to display all the Ride Content from table 

    $items['searchmyride'] = array(
        'title' => 'Search My Ride',
        'description' => 'Search Ride details to select',
        'page callback' => '_search_my_ride',
        'page arguments' => NULL,
        'access callback' => TRUE,
        'expanded' => TRUE,
    );
    return $items;
}

function displayridedetails_form_alter(&$form, &$form_state, $form_id) {

//    drupal_set_message("<pre>" . print_r($form, 1));
}

function _search_my_ride() {

    // calling Drupal predefined function to create form
    $form_tem = drupal_get_form('search_my_ride_form');

    if (isset($_POST)) {

        $formState = $_SESSION['searchMyride'];
       // drupal_set_message('<prv>' . print_r($formState['values']));
    } else {
        $formState['values'] = array();
    }
    $output = drupal_render($form_tem);


    $sql_Query = 'SELECT distinct title,field_car_model_value,
        field_start_date_rrule,field_start_time_up_value,
        field_start_time_down_value FROM node n 
        LEFT JOIN field_data_field_car_model model on model.entity_id = n.nid 
        LEFT JOIN field_data_field_start_date sdate on sdate.entity_id = n.nid
        LEFT JOIN field_data_field_start_time_down tdown on tdown.entity_id = n.nid
        LEFT JOIN field_data_field_start_time_up tup on tup.entity_id = n.nid
        LEFT JOIN field_data_field_start_location sloc on sloc.entity_id = n.nid 
        LEFT JOIN field_data_field_destination_location destloc on 
        destloc.entity_id = n.nid';

    $sql_where = ' WHERE ';
    if (isset($_POST)) {
        $values = $formState['values'];

        // from ssearch           
        $sql_where = $sql_where . ' ( sloc.field_start_location_administrative_area like \'%' . $values['from'] . '%\' OR ';
        $sql_where = $sql_where . 'sloc.field_start_location_administrative_area = \'' . $values['from'] . '\' OR ';
        $sql_where = $sql_where . 'sloc.field_start_location_locality like \'%' . $values['from'] . '%\' OR ';
        $sql_where = $sql_where . 'sloc.field_start_location_locality = \'' . $values['from'] . '\' OR ';
        $sql_where = $sql_where . 'sloc.field_start_location_postal_code like \'%' . $values['from'] . '%\' OR ';
        $sql_where = $sql_where . 'sloc.field_start_location_postal_code = \'' . $values['from'] . '\' OR ';
        $sql_where = $sql_where . 'sloc.field_start_location_thoroughfare like \'%' . $values['from'] . '%\' OR ';
        $sql_where = $sql_where . 'sloc.field_start_location_thoroughfare = \'' . $values['from'] . '\' OR ';
        $sql_where = $sql_where . 'sloc.field_start_location_premise like \'%' . $values['from'] . '%\' OR ';
        $sql_where = $sql_where . 'sloc.field_start_location_premise = \'' . $values['from'] . '\') AND ';

        // Destination
        $sql_where = $sql_where . ' ( destloc.field_destination_location_administrative_area like \'%' . $values['from'] . '%\' OR ';
        $sql_where = $sql_where . 'destloc.field_destination_location_locality like \'%' . $values['from'] . '%\' OR ';
        $sql_where = $sql_where . 'destloc.field_destination_location_postal_code like \'%' . $values['from'] . '%\' OR ';
        $sql_where = $sql_where . 'destloc.field_destination_location_thoroughfare like \'%' . $values['from'] . '%\' OR ';
        $sql_where = $sql_where . 'destloc.field_destination_location_premise like \'%' . $values['from'] . '%\' OR ';
        $sql_where = $sql_where . ' destloc.field_destination_location_administrative_area = \'' . $values['from'] . '\' OR ';
        $sql_where = $sql_where . 'destloc.field_destination_location_locality = \'' . $values['from'] . '\' OR ';
        $sql_where = $sql_where . 'destloc.field_destination_location_postal_code = \'' . $values['from'] . '\' OR ';
        $sql_where = $sql_where . 'destloc.field_destination_location_thoroughfare = \'' . $values['from'] . '\' OR ';
        $sql_where = $sql_where . 'destloc.field_destination_location_premise = \'' . $values['from'] . '\') AND ';


        // start Date 
        $time = strtotime($values['start_date']);
        $newformat = date('Y-m-d', $time);
        $sql_where = $sql_where . ' sdate.field_start_date_value > ' . $newformat . ' ';

        if ($values['repeate_flag'] != 0) {

            $dateObj = $values['date'];
            $rruleStr = $dateObj['rrule'];

            $sql_where = $sql_where . ' AND sdate.field_start_date_rrule = \'' . $rruleStr . '\'';
        }
        $sql_Query = $sql_Query . $sql_where;

        //drupal_set_message('Query '.$sql_Query);
    }

    $result = db_query($sql_Query);

    if ($result) {
        $rows = array();
        while ($row = $result->fetchAssoc()) {

            $rows[] = array_map('check_plain', $row);
        }

        $header = array(t('Title'), t('Car model'), t('Start Date Rule'),
            t('Up time'), t('Down Start time'));

        $output .= theme('table', array('header' => $header, 'rows' => $rows));
    } else {
        drupal_set_message(t('No rides Found'));
    }

    return $output;
}

function search_my_ride_form($form, &$formState) {
  //  drupal_set_message('Form loaded');
    $form = array();

    if (isset($_POST)) {
        $formStateTemp = $_SESSION['searchMyride'];
        $formState['values'] = $formStateTemp['values'];
        //drupal_set_message('<pre>' . print_r($formState, 1));
    }


    $form['from'] = array(
        '#type' => 'textfield',
        '#title' => t(' From '),
        '#required' => TRUE,
        '#default_value' => $formState['values']['from'] ? $formState['values']['from'] : '', // added default value.
        '#description' => "Please enter your from.", // added description
        '#size' => 20, // added
        '#maxlength' => 20, // added
    );
    $form['destination'] = array(
        '#type' => 'textfield',
        '#title' => t('destination'),
        '#required' => TRUE,
        '#default_value' => $formState['values']['destination'] ? $formState['values']['destination'] : '', // added default value.
        '#description' => "Please enter your destination", // added description
        '#size' => 20, // added
        '#maxlength' => 20, // added
    );
    $form['start_date'] = array(
        '#type' => 'date_popup',
        '#title' => t('Start Date'),
        '#required' => TRUE,
        '#default_value' => $formState['values']['start_date'] ? $formState['values']['start_date'] : "mm/dd/yyyy", // added default value.
        '#date_format' => 'j F Y',
        '#description' => "Please enter your start Date.", // added description
        '#size' => 20, // added
        '#maxlength' => 20, // added
        '#label' => ''
    );
    $form['repeate_flag'] = array(
        '#type' => 'checkbox',
        '#title' => 'Repeate',
        '#default_value' => $formState['values']['repeate_flag'] ? $formState['values']['repeate_flag'] : 0,
        '#attributes' => array('onClick' => 'jQuery("#repeat-settings-fieldset").toggle(this.checked);')
    );
    $form['date'] = array(
        '#tree' => TRUE,
        '#attributes' => array('onClick' => 'display:none;')
    );
    $form['date']['rrule'] = array(
        '#type' => 'date_repeat_rrule',
        '#default_value' => $formState['values']['date']['rrule'] ? $formState['values']['date']['rrule'] : '',
        //'#date_timezone' => date_default_timezone_name(),
        '#date_timezone' => date_default_timezone(),
        '#date_format' => variable_get('date_format_short', 'm/d/Y - H:i'),
        '#weight' => -9,
        '#date_year_range' => '-0:+3',
        '#date_repeat_widget' => 'date_popup_repeat',
        '#date_repeat_collapsed' => TRUE,
        '#date_label_position' => 0
    );

    $form['btn_search'] = array(
        '#type' => 'submit',
        '#value' => 'Search'
    );
    return $form;
}

function search_my_ride_form_submit($form, &$form_state) {
    //   drupal_set_message('<pre>' . print_r($form_state, 1));
    $_SESSION['searchMyride'] = $form_state;
}
